# Generated by Django 6.0.2 on 2026-02-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="port",
            name="city",
        ),
        migrations.RemoveField(
            model_name="company",
            name="city",
        ),
        migrations.RemoveField(
            model_name="company",
            name="ports",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="contact_person",
            new_name="ptc",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_type",
        ),
        migrations.RemoveField(
            model_name="company",
            name="phone",
        ),
        migrations.AddField(
            model_name="company",
            name="contact_nos",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="specialities",
            field=models.ManyToManyField(related_name="companies", to="myapp.service"),
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Port",
        ),
    ]
